services:
  bot:
    # Build the image from the Dockerfile in the current directory
    env_file: ".env"
    build: .
    networks:
      - goo
  db:
    image: postgres:17.6-bookworm
    restart: always
    env_file: ".env"
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - goo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  goo: {}
